// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               v3.5.1
// source: branch-food-map-food-channel.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "vn.techres.microservice.grpc.java.dashboard.branch_food_map_food_channel";

export interface BaseResponse {
  status: number;
  message: string;
  data: Empty | undefined;
}

export interface Empty {
}

export interface GetBranchFoodMapInformationRquest {
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  channel_order_food_id: number;
}

export interface BranchFoodMapInformationResponse {
  foods: string;
}

export interface BranchFoodMapInformationResponseBaseResponse {
  status: number;
  message: string;
  data: BranchFoodMapInformationResponse | undefined;
}

export const VN_TECHRES_MICROSERVICE_GRPC_JAVA_DASHBOARD_BRANCH_FOOD_MAP_FOOD_CHANNEL_PACKAGE_NAME =
  "vn.techres.microservice.grpc.java.dashboard.branch_food_map_food_channel";

export interface BranchFoodMapFoodChannelServiceClient {
  getBranchFoodMapInformation(
    request: GetBranchFoodMapInformationRquest,
    metadata?: Metadata,
  ): Observable<BranchFoodMapInformationResponseBaseResponse>;
}

export interface BranchFoodMapFoodChannelServiceController {
  getBranchFoodMapInformation(
    request: GetBranchFoodMapInformationRquest,
    metadata?: Metadata,
  ):
    | Promise<BranchFoodMapInformationResponseBaseResponse>
    | Observable<BranchFoodMapInformationResponseBaseResponse>
    | BranchFoodMapInformationResponseBaseResponse;
}

export function BranchFoodMapFoodChannelServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getBranchFoodMapInformation"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("BranchFoodMapFoodChannelService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("BranchFoodMapFoodChannelService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const BRANCH_FOOD_MAP_FOOD_CHANNEL_SERVICE_NAME = "BranchFoodMapFoodChannelService";
