// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               v3.5.1
// source: channel-order-food-api.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "vn.techres.microservice.grpc.nodejs_food_channel_connector.channel_order_api";

export interface GetFoodRequest {
  url: string;
  access_token: string;
  channel_branch_id: string;
  merchant_id: string;
  channel_order_food_id: number;
  url_get_account_information_detail: string;
}

export interface FoodChannelOrderFood {
  id: string;
  name: string;
  price: string;
  picture_url: string;
  description: string;
  is_pending: number;
}

export interface ListFoodBaseResponse {
  status: number;
  message: string;
  data: FoodChannelOrderFood[];
}

export interface UpdatePriceFoodsSHFRequest {
  foods: string;
  url: string;
  access_token: string;
  channel_branch_id: number;
}

export interface EmptyBaseResponse {
  status: number;
  message: string;
  data: Empty | undefined;
}

export interface Empty {
}

export interface UpdatePriceFoodsBEFRequest {
  foods: string;
  url_food_detail: string;
  url_food_update: string;
  access_token: string;
  channel_branch_id: string;
  merchant_id: string;
}

export interface GetBranchRequest {
  url: string;
  access_token: string;
  username: string;
  channel_order_food_id: number;
}

export interface BranchChannelOrderFood {
  branch_id: string;
  branch_name: string;
  merchant_id: string;
}

export interface ListBranchBaseResponse {
  status: number;
  message: string;
  data: BranchChannelOrderFood[];
}

export interface CheckTokenGRFRequest {
  url_logout: string;
  url_update_device: string;
  username: string;
  password: string;
  device_id: string;
  device_brand: string;
}

export interface CheckTokenGRF {
  access_token: string;
}

export interface CheckTokenGRFBaseResponse {
  status: number;
  message: string;
  data: CheckTokenGRF | undefined;
}

export interface CheckTokenBEFRequest {
  url_login: string;
  username: string;
  password: string;
}

export interface CheckTokenBEF {
  access_token: string;
  user_id: number;
}

export interface CheckTokenBEFBaseResponse {
  status: number;
  message: string;
  data: CheckTokenBEF | undefined;
}

export interface UpdateOrderStatusRequest {
  channel_orders: string;
}

export interface OrderStatus {
  id: number;
  status: number;
  status_string: string;
}

export interface ListOrderStatusBaseResponse {
  status: number;
  message: string;
  data: OrderStatus[];
}

export interface ReconnectionTokenGRFRequest {
  url_login: string;
  url_update_device: string;
  username: string;
  password: string;
  device_id: string;
  device_brand: string;
}

export interface ReconnectionTokenBEFRequest {
  url_login: string;
  username: string;
  password: string;
}

export interface CheckTokenAllFoodChannelRequest {
  tokens: string;
}

export interface ResultBaseResponse {
  status: number;
  message: string;
  data: ErrorResponse[];
}

export interface ErrorResponse {
  code: string;
  message: string;
  channel_order_food_token_id: number;
}

export interface GetChannelBranchesRequest {
  restaurant_brand_id: number;
  tokens: string;
}

export interface ChannelBranchesResponse {
  branch_id: string;
  branch_name: string;
  channel_order_food_token_id: number;
  channel_order_food_token_name: string;
  merchant_id: string;
  branch_address: string;
  branch_phone: string;
}

export interface ListChannelBranchesResponse {
  status: number;
  message: string;
  data: ChannelBranchesResponse[];
}

export interface SyncChannelOrdersRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  tokens: string;
}

export interface SyncChannelOrderHistoriesRequest {
  tokens: string;
  time: string;
}

export interface SyncChannelOrderHistoriesResponse {
  history_orders_SHF: string;
  history_orders_GRF: string;
  history_orders_BEF: string;
}

export interface SyncChannelOrderHistoryBaseResponse {
  status: number;
  message: string;
  data: SyncChannelOrderHistoriesResponse | undefined;
}

export interface GetFoodToppingRequest {
  url: string;
  access_token: string;
  channel_branch_id: string;
  merchant_id: string;
  channel_order_food_id: number;
  url_get_account_information_detail: string;
}

export interface GroupFoodToppingResponse {
  id: string;
  name: string;
  list: FoodToppingResponse[];
}

export interface FoodToppingResponse {
  id: string;
  name: string;
  price: string;
}

export interface ListFoodToppingResponse {
  status: number;
  message: string;
  data: GroupFoodToppingResponse[];
}

/** ---------------------- confirmChannelOrder ------------------------ */
export interface ConfirmChannelOrderRequest {
  url_comfirm_order: string;
  access_token: string;
  channel_branch_id: string;
  merchant_id: string;
  channel_order_food_id: number;
  url_login: string;
  url_update_device: string;
  url_get_branch_detail: string;
  username: string;
  password: string;
  order_id: string;
  user_id: number;
  device_id: string;
  device_brand: string;
}

export interface GetEarningSumaryReportRequest {
  tokens: string;
  from_date: string;
  to_date: string;
}

export interface EarningSumaryReportResponse {
  net_sales: number;
  net_total: number;
  total_orders: number;
  breakdown_by_category: string;
}

export interface EarningSumaryReportResultResponse {
  status: number;
  message: string;
  data: EarningSumaryReportResponse | undefined;
}

export const VN_TECHRES_MICROSERVICE_GRPC_NODEJS_FOOD_CHANNEL_CONNECTOR_CHANNEL_ORDER_API_PACKAGE_NAME =
  "vn.techres.microservice.grpc.nodejs_food_channel_connector.channel_order_api";

export interface ChannelOrderFoodApiServiceClient {
  getFoods(request: GetFoodRequest, metadata?: Metadata): Observable<ListFoodBaseResponse>;

  updatePriceFoodsShf(request: UpdatePriceFoodsSHFRequest, metadata?: Metadata): Observable<EmptyBaseResponse>;

  updatePriceFoodsBef(request: UpdatePriceFoodsBEFRequest, metadata?: Metadata): Observable<EmptyBaseResponse>;

  getBranches(request: GetBranchRequest, metadata?: Metadata): Observable<ListBranchBaseResponse>;

  checkTokenGrf(request: CheckTokenGRFRequest, metadata?: Metadata): Observable<CheckTokenGRFBaseResponse>;

  checkTokenBef(request: CheckTokenBEFRequest, metadata?: Metadata): Observable<CheckTokenBEFBaseResponse>;

  updateOrderStatus(request: UpdateOrderStatusRequest, metadata?: Metadata): Observable<ListOrderStatusBaseResponse>;

  reconnectionTokenGrf(
    request: ReconnectionTokenGRFRequest,
    metadata?: Metadata,
  ): Observable<CheckTokenGRFBaseResponse>;

  reconnectionTokenBef(
    request: ReconnectionTokenBEFRequest,
    metadata?: Metadata,
  ): Observable<CheckTokenBEFBaseResponse>;

  checkTokenAllFoodChannel(
    request: CheckTokenAllFoodChannelRequest,
    metadata?: Metadata,
  ): Observable<ResultBaseResponse>;

  getChannelBranches(request: GetChannelBranchesRequest, metadata?: Metadata): Observable<ListChannelBranchesResponse>;

  syncChannelOrders(request: SyncChannelOrdersRequest, metadata?: Metadata): Observable<EmptyBaseResponse>;

  syncChannelOrderHistories(
    request: SyncChannelOrderHistoriesRequest,
    metadata?: Metadata,
  ): Observable<SyncChannelOrderHistoryBaseResponse>;

  getFoodToppings(request: GetFoodToppingRequest, metadata?: Metadata): Observable<ListFoodToppingResponse>;

  confirmChannelOrder(request: ConfirmChannelOrderRequest, metadata?: Metadata): Observable<EmptyBaseResponse>;

  getEarningSumaryReport(
    request: GetEarningSumaryReportRequest,
    metadata?: Metadata,
  ): Observable<EarningSumaryReportResultResponse>;

  getEarningSumaryReportV2(
    request: GetEarningSumaryReportRequest,
    metadata?: Metadata,
  ): Observable<EarningSumaryReportResultResponse>;
}

export interface ChannelOrderFoodApiServiceController {
  getFoods(
    request: GetFoodRequest,
    metadata?: Metadata,
  ): Promise<ListFoodBaseResponse> | Observable<ListFoodBaseResponse> | ListFoodBaseResponse;

  updatePriceFoodsShf(
    request: UpdatePriceFoodsSHFRequest,
    metadata?: Metadata,
  ): Promise<EmptyBaseResponse> | Observable<EmptyBaseResponse> | EmptyBaseResponse;

  updatePriceFoodsBef(
    request: UpdatePriceFoodsBEFRequest,
    metadata?: Metadata,
  ): Promise<EmptyBaseResponse> | Observable<EmptyBaseResponse> | EmptyBaseResponse;

  getBranches(
    request: GetBranchRequest,
    metadata?: Metadata,
  ): Promise<ListBranchBaseResponse> | Observable<ListBranchBaseResponse> | ListBranchBaseResponse;

  checkTokenGrf(
    request: CheckTokenGRFRequest,
    metadata?: Metadata,
  ): Promise<CheckTokenGRFBaseResponse> | Observable<CheckTokenGRFBaseResponse> | CheckTokenGRFBaseResponse;

  checkTokenBef(
    request: CheckTokenBEFRequest,
    metadata?: Metadata,
  ): Promise<CheckTokenBEFBaseResponse> | Observable<CheckTokenBEFBaseResponse> | CheckTokenBEFBaseResponse;

  updateOrderStatus(
    request: UpdateOrderStatusRequest,
    metadata?: Metadata,
  ): Promise<ListOrderStatusBaseResponse> | Observable<ListOrderStatusBaseResponse> | ListOrderStatusBaseResponse;

  reconnectionTokenGrf(
    request: ReconnectionTokenGRFRequest,
    metadata?: Metadata,
  ): Promise<CheckTokenGRFBaseResponse> | Observable<CheckTokenGRFBaseResponse> | CheckTokenGRFBaseResponse;

  reconnectionTokenBef(
    request: ReconnectionTokenBEFRequest,
    metadata?: Metadata,
  ): Promise<CheckTokenBEFBaseResponse> | Observable<CheckTokenBEFBaseResponse> | CheckTokenBEFBaseResponse;

  checkTokenAllFoodChannel(
    request: CheckTokenAllFoodChannelRequest,
    metadata?: Metadata,
  ): Promise<ResultBaseResponse> | Observable<ResultBaseResponse> | ResultBaseResponse;

  getChannelBranches(
    request: GetChannelBranchesRequest,
    metadata?: Metadata,
  ): Promise<ListChannelBranchesResponse> | Observable<ListChannelBranchesResponse> | ListChannelBranchesResponse;

  syncChannelOrders(
    request: SyncChannelOrdersRequest,
    metadata?: Metadata,
  ): Promise<EmptyBaseResponse> | Observable<EmptyBaseResponse> | EmptyBaseResponse;

  syncChannelOrderHistories(
    request: SyncChannelOrderHistoriesRequest,
    metadata?: Metadata,
  ):
    | Promise<SyncChannelOrderHistoryBaseResponse>
    | Observable<SyncChannelOrderHistoryBaseResponse>
    | SyncChannelOrderHistoryBaseResponse;

  getFoodToppings(
    request: GetFoodToppingRequest,
    metadata?: Metadata,
  ): Promise<ListFoodToppingResponse> | Observable<ListFoodToppingResponse> | ListFoodToppingResponse;

  confirmChannelOrder(
    request: ConfirmChannelOrderRequest,
    metadata?: Metadata,
  ): Promise<EmptyBaseResponse> | Observable<EmptyBaseResponse> | EmptyBaseResponse;

  getEarningSumaryReport(
    request: GetEarningSumaryReportRequest,
    metadata?: Metadata,
  ):
    | Promise<EarningSumaryReportResultResponse>
    | Observable<EarningSumaryReportResultResponse>
    | EarningSumaryReportResultResponse;

  getEarningSumaryReportV2(
    request: GetEarningSumaryReportRequest,
    metadata?: Metadata,
  ):
    | Promise<EarningSumaryReportResultResponse>
    | Observable<EarningSumaryReportResultResponse>
    | EarningSumaryReportResultResponse;
}

export function ChannelOrderFoodApiServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getFoods",
      "updatePriceFoodsShf",
      "updatePriceFoodsBef",
      "getBranches",
      "checkTokenGrf",
      "checkTokenBef",
      "updateOrderStatus",
      "reconnectionTokenGrf",
      "reconnectionTokenBef",
      "checkTokenAllFoodChannel",
      "getChannelBranches",
      "syncChannelOrders",
      "syncChannelOrderHistories",
      "getFoodToppings",
      "confirmChannelOrder",
      "getEarningSumaryReport",
      "getEarningSumaryReportV2",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ChannelOrderFoodApiService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ChannelOrderFoodApiService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CHANNEL_ORDER_FOOD_API_SERVICE_NAME = "ChannelOrderFoodApiService";
