// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               v3.5.1
// source: complete-order.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "vn.techres.microservice.grpc.java.order.order";

export interface DeliveringOrderRequest {
  order_id: number;
}

export interface CompleteOrderRequest {
  order_id: number;
}

export interface CompleteOrderAppFoodRequest {
  order_ids: string;
}

export interface BaseResponse {
  status: number;
  message: string;
  data: string;
}

export const VN_TECHRES_MICROSERVICE_GRPC_JAVA_ORDER_ORDER_PACKAGE_NAME =
  "vn.techres.microservice.grpc.java.order.order";

export interface OrderServiceClient {
  complete(request: CompleteOrderRequest, metadata?: Metadata): Observable<BaseResponse>;

  updateOrderDelivering(request: DeliveringOrderRequest, metadata?: Metadata): Observable<BaseResponse>;

  completeAppFood(request: CompleteOrderAppFoodRequest, metadata?: Metadata): Observable<BaseResponse>;

  closeAppFood(request: CompleteOrderRequest, metadata?: Metadata): Observable<BaseResponse>;

  completeV2(request: CompleteOrderRequest, metadata?: Metadata): Observable<BaseResponse>;

  completeAppFoodV2(request: CompleteOrderAppFoodRequest, metadata?: Metadata): Observable<BaseResponse>;

  closeAppFoodV2(request: CompleteOrderAppFoodRequest, metadata?: Metadata): Observable<BaseResponse>;
}

export interface OrderServiceController {
  complete(
    request: CompleteOrderRequest,
    metadata?: Metadata,
  ): Promise<BaseResponse> | Observable<BaseResponse> | BaseResponse;

  updateOrderDelivering(
    request: DeliveringOrderRequest,
    metadata?: Metadata,
  ): Promise<BaseResponse> | Observable<BaseResponse> | BaseResponse;

  completeAppFood(
    request: CompleteOrderAppFoodRequest,
    metadata?: Metadata,
  ): Promise<BaseResponse> | Observable<BaseResponse> | BaseResponse;

  closeAppFood(
    request: CompleteOrderRequest,
    metadata?: Metadata,
  ): Promise<BaseResponse> | Observable<BaseResponse> | BaseResponse;

  completeV2(
    request: CompleteOrderRequest,
    metadata?: Metadata,
  ): Promise<BaseResponse> | Observable<BaseResponse> | BaseResponse;

  completeAppFoodV2(
    request: CompleteOrderAppFoodRequest,
    metadata?: Metadata,
  ): Promise<BaseResponse> | Observable<BaseResponse> | BaseResponse;

  closeAppFoodV2(
    request: CompleteOrderAppFoodRequest,
    metadata?: Metadata,
  ): Promise<BaseResponse> | Observable<BaseResponse> | BaseResponse;
}

export function OrderServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "complete",
      "updateOrderDelivering",
      "completeAppFood",
      "closeAppFood",
      "completeV2",
      "completeAppFoodV2",
      "closeAppFoodV2",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ORDER_SERVICE_NAME = "OrderService";
