// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               v3.5.1
// source: confirm-order-channel.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "vn.techres.microservice.grpc.java.java_order_process_three.confirm_order_channel";

export interface BaseConfirmOrderChannelRequest {
  branch_id: number;
  confirm_order_channel_requests: ConfirmOrderChannelRequest[];
}

export interface ConfirmOrderChannelRequest {
  id: number;
  order_id: string;
  channel_order_food_id: number;
  channel_branch_id: string;
  total_amount: string;
  driver_name: string;
  driver_avatar: string;
  channel_order_food_name: string;
  channel_order_food_code: string;
  details: OrderChannelDetailRequest[];
  display_id: string;
  discount_amount: string;
  restaurant_order_id: number;
  customer_order_amount: string;
  customer_discount_amount: string;
  order_amount: string;
  driver_phone: string;
  customer_name: string;
  phone: string;
  address: string;
  shipping_fee: string;
  create_at: string;
  channel_branch_name: string;
  channel_branch_address: string;
  channel_branch_phone: string;
  note: string;
  item_discount_amount: string;
  status_string: string;
}

export interface OrderChannelDetailRequest {
  id: number;
  channel_order_id: number;
  order_id: string;
  channel_order_food_id: number;
  food_id: string;
  food_name: string;
  quantity: number;
  food_price: string;
  food_note: string;
  food_options: string;
  food_price_addition: string;
  discount_food_price: string;
}

export interface OrderChannelDetailResponse {
  id: number;
  channel_order_id: number;
  order_id: string;
  channel_order_food_id: number;
  food_id: string;
  food_name: string;
  quantity: number;
  price: string;
  note: string;
  food_options: AdditionFoodAppFoodResponse[];
  food_price_addition: string;
}

export interface AdditionFoodAppFoodResponse {
  id: string;
  name: string;
  price: string;
  quantity: number;
}

export interface ConfirmOrderChannelResponse {
  channel_order_update_json: string;
}

export interface FoodNoteResponse {
  food_note_id: number;
  food_note: string;
}

export interface BaseConfirmOrderChannelResponse {
  status: number;
  message: string;
  data: ConfirmOrderChannelResponse | undefined;
}

export const VN_TECHRES_MICROSERVICE_GRPC_JAVA_JAVA_ORDER_PROCESS_THREE_CONFIRM_ORDER_CHANNEL_PACKAGE_NAME =
  "vn.techres.microservice.grpc.java.java_order_process_three.confirm_order_channel";

export interface ConfirmOrderChannelServiceClient {
  confirmOrderChannel(
    request: BaseConfirmOrderChannelRequest,
    metadata?: Metadata,
  ): Observable<BaseConfirmOrderChannelResponse>;

  confirmOrderChanneV2(
    request: BaseConfirmOrderChannelRequest,
    metadata?: Metadata,
  ): Observable<BaseConfirmOrderChannelResponse>;
}

export interface ConfirmOrderChannelServiceController {
  confirmOrderChannel(
    request: BaseConfirmOrderChannelRequest,
    metadata?: Metadata,
  ):
    | Promise<BaseConfirmOrderChannelResponse>
    | Observable<BaseConfirmOrderChannelResponse>
    | BaseConfirmOrderChannelResponse;

  confirmOrderChanneV2(
    request: BaseConfirmOrderChannelRequest,
    metadata?: Metadata,
  ):
    | Promise<BaseConfirmOrderChannelResponse>
    | Observable<BaseConfirmOrderChannelResponse>
    | BaseConfirmOrderChannelResponse;
}

export function ConfirmOrderChannelServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["confirmOrderChannel", "confirmOrderChanneV2"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ConfirmOrderChannelService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ConfirmOrderChannelService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CONFIRM_ORDER_CHANNEL_SERVICE_NAME = "ConfirmOrderChannelService";
