// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               v3.5.1
// source: customer-order-for-channel-food.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage =
  "vn.techres.microservice.grpc.java.customer_order_online.customer_order_for_channel_food";

export interface CustomerOrderRequest {
  branch_id: number;
  customer_order_type: number;
  customer_order_status: string;
}

export interface CustomerOrderDetailRequest {
  id: number;
}

export interface BaseListResponse {
  status: number;
  message: string;
  data: CustomerOrderOnlineResponse[];
  is_have_new_order: number;
}

export interface BaseDetailResponse {
  status: number;
  message: string;
  data: CustomerOrderOnlineResponse | undefined;
}

export interface CustomerOrderOnlineResponse {
  id: number;
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  order_id: number;
  customer_id: number;
  area_id: number;
  table_id: number;
  table_name: string;
  customer_name: string;
  phone: string;
  address: string;
  total_amount: string;
  payment_status: number;
  payment_method: number;
  note: string;
  customer_order_status: number;
  customer_order_type: number;
  customer_order_details: CustomerOrderOnlineDetailResponse[];
  created_at: string;
  updated_at: string;
  shipping_fee: string;
  restaurant_third_party_delivery_id: number;
  shipping_lat: string;
  shipping_lng: string;
  third_party_delivery_order_id: string;
  tracking_url: string;
  shipper_name: string;
  shipper_phone: string;
  order_time: number;
  cancel_comment: string;
  third_party_delivery_name: string;
  is_pre_order: number;
  pre_order_time: string;
}

export interface FoodInComboResponse {
  id: number;
  name: string;
  price: string;
  quantity: string;
}

export interface FoodInAdditionResponse {
  id: number;
  name: string;
  price_with_temporary: string;
  quantity: string;
}

export interface CustomerOrderOnlineDetailResponse {
  id: number;
  customer_order_id: number;
  food_id: number;
  food_name: string;
  order_detail_parent_id: number;
  order_detail_combo_parent_id: number;
  customer_order_detail_addition_ids: string;
  customer_order_detail_combo_ids: string;
  quantity: string;
  price: string;
  total_price: string;
  is_addition: number;
  is_combo: number;
  note: string;
  customer_order_detail_combo: FoodInComboResponse[];
  customer_order_detail_addition: FoodInAdditionResponse[];
  total_price_addition: string;
  created_at: string;
  updated_at: string;
}

export const VN_TECHRES_MICROSERVICE_GRPC_JAVA_CUSTOMER_ORDER_ONLINE_CUSTOMER_ORDER_FOR_CHANNEL_FOOD_PACKAGE_NAME =
  "vn.techres.microservice.grpc.java.customer_order_online.customer_order_for_channel_food";

export interface CustomerOrderForChannelFoodServiceClient {
  getList(request: CustomerOrderRequest, metadata?: Metadata): Observable<BaseListResponse>;

  getDetail(request: CustomerOrderDetailRequest, metadata?: Metadata): Observable<BaseDetailResponse>;
}

export interface CustomerOrderForChannelFoodServiceController {
  getList(
    request: CustomerOrderRequest,
    metadata?: Metadata,
  ): Promise<BaseListResponse> | Observable<BaseListResponse> | BaseListResponse;

  getDetail(
    request: CustomerOrderDetailRequest,
    metadata?: Metadata,
  ): Promise<BaseDetailResponse> | Observable<BaseDetailResponse> | BaseDetailResponse;
}

export function CustomerOrderForChannelFoodServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getList", "getDetail"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("CustomerOrderForChannelFoodService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("CustomerOrderForChannelFoodService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CUSTOMER_ORDER_FOR_CHANNEL_FOOD_SERVICE_NAME = "CustomerOrderForChannelFoodService";
