// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               v3.5.1
// source: order-app-food.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "vn.techres.microservice.grpc.java.customer_order_online.order_online";

export interface OrderAppFoodRequest {
  branch_id: number;
  total_amount: string;
  channel_order_id: number;
  channel_order_code: string;
  details: OrderAppFoodDetailRequest[];
}

export interface OrderAppFoodDetailRequest {
  food_id: number;
  food_name: string;
  quantity: number;
  price: string;
}

export interface BaseResponse {
  status: number;
  message: string;
  data: OrderAppFoodResponse | undefined;
}

export interface OrderAppFoodResponse {
  id: number;
  total_amount: string;
}

export const VN_TECHRES_MICROSERVICE_GRPC_JAVA_CUSTOMER_ORDER_ONLINE_ORDER_ONLINE_PACKAGE_NAME =
  "vn.techres.microservice.grpc.java.customer_order_online.order_online";

export interface OrderAppFoodServiceClient {
  create(request: OrderAppFoodRequest, metadata?: Metadata): Observable<BaseResponse>;
}

export interface OrderAppFoodServiceController {
  create(
    request: OrderAppFoodRequest,
    metadata?: Metadata,
  ): Promise<BaseResponse> | Observable<BaseResponse> | BaseResponse;
}

export function OrderAppFoodServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["create"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OrderAppFoodService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OrderAppFoodService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ORDER_APP_FOOD_SERVICE_NAME = "OrderAppFoodService";
