// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               v3.5.1
// source: sync-connector-channel-order.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage =
  "vn.techres.microservice.grpc.nodejs_food_channel_connector.sync_connector_channel_order";

export interface EmptyBaseResponse {
  status: number;
  message: string;
  data: Empty | undefined;
}

export interface Empty {
}

export interface SyncChannelOrderShfRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  tokens: string;
}

export interface SyncChannelOrderGrfRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  tokens: string;
}

export interface SyncChannelOrderBefRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  tokens: string;
}

export interface HealthCheckRequest {
}

export interface HealthCheckGRPCResponse {
  status: number;
  message: string;
  data: string;
}

export const VN_TECHRES_MICROSERVICE_GRPC_NODEJS_FOOD_CHANNEL_CONNECTOR_SYNC_CONNECTOR_CHANNEL_ORDER_PACKAGE_NAME =
  "vn.techres.microservice.grpc.nodejs_food_channel_connector.sync_connector_channel_order";

export interface SyncConnectorChannelOrderServiceClient {
  syncChannelOrderShf(request: SyncChannelOrderShfRequest, metadata?: Metadata): Observable<EmptyBaseResponse>;

  syncChannelOrderGrf(request: SyncChannelOrderGrfRequest, metadata?: Metadata): Observable<EmptyBaseResponse>;

  syncChannelOrderBef(request: SyncChannelOrderBefRequest, metadata?: Metadata): Observable<EmptyBaseResponse>;

  healthCheckShf(request: HealthCheckRequest, metadata?: Metadata): Observable<HealthCheckGRPCResponse>;

  healthCheckGrf(request: HealthCheckRequest, metadata?: Metadata): Observable<HealthCheckGRPCResponse>;

  healthCheckBef(request: HealthCheckRequest, metadata?: Metadata): Observable<HealthCheckGRPCResponse>;
}

export interface SyncConnectorChannelOrderServiceController {
  syncChannelOrderShf(
    request: SyncChannelOrderShfRequest,
    metadata?: Metadata,
  ): Promise<EmptyBaseResponse> | Observable<EmptyBaseResponse> | EmptyBaseResponse;

  syncChannelOrderGrf(
    request: SyncChannelOrderGrfRequest,
    metadata?: Metadata,
  ): Promise<EmptyBaseResponse> | Observable<EmptyBaseResponse> | EmptyBaseResponse;

  syncChannelOrderBef(
    request: SyncChannelOrderBefRequest,
    metadata?: Metadata,
  ): Promise<EmptyBaseResponse> | Observable<EmptyBaseResponse> | EmptyBaseResponse;

  healthCheckShf(
    request: HealthCheckRequest,
    metadata?: Metadata,
  ): Promise<HealthCheckGRPCResponse> | Observable<HealthCheckGRPCResponse> | HealthCheckGRPCResponse;

  healthCheckGrf(
    request: HealthCheckRequest,
    metadata?: Metadata,
  ): Promise<HealthCheckGRPCResponse> | Observable<HealthCheckGRPCResponse> | HealthCheckGRPCResponse;

  healthCheckBef(
    request: HealthCheckRequest,
    metadata?: Metadata,
  ): Promise<HealthCheckGRPCResponse> | Observable<HealthCheckGRPCResponse> | HealthCheckGRPCResponse;
}

export function SyncConnectorChannelOrderServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "syncChannelOrderShf",
      "syncChannelOrderGrf",
      "syncChannelOrderBef",
      "healthCheckShf",
      "healthCheckGrf",
      "healthCheckBef",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("SyncConnectorChannelOrderService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("SyncConnectorChannelOrderService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const SYNC_CONNECTOR_CHANNEL_ORDER_SERVICE_NAME = "SyncConnectorChannelOrderService";
