// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               v3.5.1
// source: user.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "vn.techres.grpc.nodejs.user.service";

export interface Empty {
}

export interface UserDetailDTO {
  user_id: number;
}

export interface UserResponse {
  id: number;
  company_id: number;
  role_id: number;
  country_id: number;
  first_name: string;
  last_name: string;
  phone_country_code: string;
  phone_number: string;
  email: string;
  password: string;
  avatar: string;
  identification_number: string;
  gender: number;
  birthday: string;
  position: string;
  introduction: string;
  account_type: number;
  is_show_on_e_namecard: number;
  is_active: number;
  created_at: string;
  updated_at: string;
}

export interface BaseResponse {
  status: number;
  message: string;
  data: UserResponse | undefined;
}

export const VN_TECHRES_GRPC_NODEJS_USER_SERVICE_PACKAGE_NAME = "vn.techres.grpc.nodejs.user.service";

export interface UserServiceClient {
  spGUser(request: UserDetailDTO, metadata?: Metadata): Observable<BaseResponse>;
}

export interface UserServiceController {
  spGUser(request: UserDetailDTO, metadata?: Metadata): Promise<BaseResponse> | Observable<BaseResponse> | BaseResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["spGUser"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
