@startuml change-mst-user

actor User
participant "Gateway" as Gateway
participant "Food Channel Controller" as FoodChannelController
participant "Food Channel Validator" as FoodChannelValidator
participant "Food Channel Processor" as FoodChannelProcessor
participant "Food Channel Connector" as FoodChannelConnector
participant "Shopee Food" as ShopeeFood
participant "Grab Food" as GrabFood
participant "Bee Food" as BeeFood

User -> Gateway: API: channel-order-histories
Gateway -> FoodChannelController: HttpsRequest
FoodChannelController -> FoodChannelValidator: validateGRPC(branchId)

activate FoodChannelValidator
FoodChannelValidator --> FoodChannelController: return data
alt Branch does not exist
    deactivate FoodChannelValidator
    activate FoodChannelController
    FoodChannelController -->> User: return error
    deactivate FoodChannelController
end alt

FoodChannelController ->> FoodChannelProcessor: syncOrderHistoriesGRPC(branchId)
activate FoodChannelProcessor
FoodChannelProcessor ->> FoodChannelProcessor: checkSyncLatest(branchId)
deactivate FoodChannelProcessor

FoodChannelProcessor ->> FoodChannelConnector: syncOrderHistoriesGRPC(branchId, date)
activate FoodChannelConnector

note over FoodChannelConnector #C0C0C0: Start <<worker threads>>

note right of FoodChannelConnector: Shopee food worker
FoodChannelConnector ->> ShopeeFood: refreshToken()
activate ShopeeFood
ShopeeFood -->> FoodChannelConnector: return refreshToken()
deactivate ShopeeFood

alt refreshToken Success
    FoodChannelConnector ->> ShopeeFood: getListOrder(branchId, date)
    activate ShopeeFood
    ShopeeFood -->> FoodChannelConnector: return ListOrder
    deactivate ShopeeFood

    loop order in getListOrder
        FoodChannelConnector ->> ShopeeFood: getDetailOrder(orderId)
        activate ShopeeFood
        ShopeeFood -->> FoodChannelConnector: return OrderDetail
        deactivate ShopeeFood

        FoodChannelConnector ->> FoodChannelConnector: Mapper(orderDetail)
    end loop
else refreshToken Failure
    note right of FoodChannelConnector #FF4500: Retry 3 times...
end alt

note right of FoodChannelConnector: Grab Food worker
FoodChannelConnector ->> GrabFood: refreshToken()
activate GrabFood
GrabFood -->> FoodChannelConnector: return refreshToken()
deactivate GrabFood

alt refreshToken Success
    FoodChannelConnector ->> GrabFood: getListOrder(branchId, date)
    activate GrabFood
    GrabFood -->> FoodChannelConnector: return ListOrder
    deactivate GrabFood

    loop order in getListOrder
        FoodChannelConnector ->> GrabFood: getDetailOrder(orderId)
        activate GrabFood
        GrabFood -->> FoodChannelConnector: return OrderDetail
        deactivate GrabFood

        FoodChannelConnector ->> FoodChannelConnector: Mapper(orderDetail)
    end loop
else refreshToken Failure
    note right of FoodChannelConnector #FF4500: Retry 3 times each 2s...
end alt

note right of FoodChannelConnector: Bee Food worker

alt Call API Success
    FoodChannelConnector ->> BeeFood: getListOrder(branchId, date)
    activate BeeFood
    BeeFood -->> FoodChannelConnector: return ListOrder
    deactivate BeeFood
else Call API Failure
    FoodChannelConnector -->> FoodChannelConnector: return[]
end alt


note over FoodChannelConnector #C0C0C0: End <<worker threads>>
FoodChannelConnector ->> FoodChannelConnector: mapper(ListOrder)
FoodChannelConnector ->> FoodChannelProcessor: mapperGRPC(ListOrder)

@enduml
