// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               v3.5.1
// source: channel-order-food-token.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "vn.techres.microservice.grpc.nodejs_food_channel_processor.channel_order_food_token";

export interface CreateChannelOrderFoodTokenRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  channel_order_food_id: number;
  access_token: string;
  username: string;
  password: string;
  x_merchant_token: string;
  device_id: string;
  device_brand: string;
  quantity_account: number;
}

export interface ChannelOrderFoodToken {
  id: number;
  restaurant_id: number;
  restaurant_brand_id: number;
  channel_order_food_id: number;
  access_token: string;
  username: string;
  password: string;
  x_foody_entity_id: number;
  x_merchant_token: string;
  device_id: string;
  device_brand: string;
  uuid: string;
  menu_group_id: string;
  name: string;
  is_connection: number;
}

export interface BaseResponse {
  status: number;
  message: string;
  data: ChannelOrderFoodToken | undefined;
}

export interface BaseListResponse {
  status: number;
  message: string;
  data: ChannelOrderFoodToken[];
}

export interface UpdateChannelOrderFoodTokenRequest {
  id: number;
  access_token: string;
  username: string;
  password: string;
  x_merchant_token: string;
  device_id: string;
  device_brand: string;
  restaurant_id: number;
}

export interface FindByIdTokenRequest {
  id: number;
}

export interface ChangeConnectionTokenRequest {
  id: number;
  quantity_account: number;
}

export interface GetListTokenRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  channel_order_food_id: number;
  channel_order_food_token_id: number;
  is_connection: number;
}

export const VN_TECHRES_MICROSERVICE_GRPC_NODEJS_FOOD_CHANNEL_PROCESSOR_CHANNEL_ORDER_FOOD_TOKEN_PACKAGE_NAME =
  "vn.techres.microservice.grpc.nodejs_food_channel_processor.channel_order_food_token";

export interface ChannelOrderFoodTokenServiceClient {
  createToken(request: CreateChannelOrderFoodTokenRequest, metadata?: Metadata): Observable<BaseResponse>;

  updateToken(request: UpdateChannelOrderFoodTokenRequest, metadata?: Metadata): Observable<BaseResponse>;

  findByIdToken(request: FindByIdTokenRequest, metadata?: Metadata): Observable<BaseResponse>;

  changeConnection(request: ChangeConnectionTokenRequest, metadata?: Metadata): Observable<BaseResponse>;

  getList(request: GetListTokenRequest, metadata?: Metadata): Observable<BaseListResponse>;
}

export interface ChannelOrderFoodTokenServiceController {
  createToken(
    request: CreateChannelOrderFoodTokenRequest,
    metadata?: Metadata,
  ): Promise<BaseResponse> | Observable<BaseResponse> | BaseResponse;

  updateToken(
    request: UpdateChannelOrderFoodTokenRequest,
    metadata?: Metadata,
  ): Promise<BaseResponse> | Observable<BaseResponse> | BaseResponse;

  findByIdToken(
    request: FindByIdTokenRequest,
    metadata?: Metadata,
  ): Promise<BaseResponse> | Observable<BaseResponse> | BaseResponse;

  changeConnection(
    request: ChangeConnectionTokenRequest,
    metadata?: Metadata,
  ): Promise<BaseResponse> | Observable<BaseResponse> | BaseResponse;

  getList(
    request: GetListTokenRequest,
    metadata?: Metadata,
  ): Promise<BaseListResponse> | Observable<BaseListResponse> | BaseListResponse;
}

export function ChannelOrderFoodTokenServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createToken", "updateToken", "findByIdToken", "changeConnection", "getList"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ChannelOrderFoodTokenService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ChannelOrderFoodTokenService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CHANNEL_ORDER_FOOD_TOKEN_SERVICE_NAME = "ChannelOrderFoodTokenService";
