// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               v3.5.1
// source: food-channel-setting-server.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "vn.techres.microservice.grpc.nodejs_food_channel_setting";

export interface Empty {
}

export interface BaseEmptyResponse {
  status: number;
  message: string;
  data: Empty | undefined;
}

export interface UpdateSettingFoodChannelBranchRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  quantity_slot_SHF: number;
  quantity_slot_GRF: number;
  quantity_slot_BEF: number;
}

export interface UpdateSettingFoodChannelRestaurantBrandRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  quantity_account_SHF: number;
  quantity_account_GRF: number;
  quantity_account_BEF: number;
}

export const VN_TECHRES_MICROSERVICE_GRPC_NODEJS_FOOD_CHANNEL_SETTING_PACKAGE_NAME =
  "vn.techres.microservice.grpc.nodejs_food_channel_setting";

export interface FoodChannelSettingServiceClient {
  updateSettingFoodChannelBranch(
    request: UpdateSettingFoodChannelBranchRequest,
    metadata?: Metadata,
  ): Observable<BaseEmptyResponse>;

  updateSettingFoodChannelRestaurantBrand(
    request: UpdateSettingFoodChannelRestaurantBrandRequest,
    metadata?: Metadata,
  ): Observable<BaseEmptyResponse>;
}

export interface FoodChannelSettingServiceController {
  updateSettingFoodChannelBranch(
    request: UpdateSettingFoodChannelBranchRequest,
    metadata?: Metadata,
  ): Promise<BaseEmptyResponse> | Observable<BaseEmptyResponse> | BaseEmptyResponse;

  updateSettingFoodChannelRestaurantBrand(
    request: UpdateSettingFoodChannelRestaurantBrandRequest,
    metadata?: Metadata,
  ): Promise<BaseEmptyResponse> | Observable<BaseEmptyResponse> | BaseEmptyResponse;
}

export function FoodChannelSettingServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["updateSettingFoodChannelBranch", "updateSettingFoodChannelRestaurantBrand"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("FoodChannelSettingService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("FoodChannelSettingService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const FOOD_CHANNEL_SETTING_SERVICE_NAME = "FoodChannelSettingService";
