// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               v3.5.1
// source: channel-order-food-report.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "vn.techres.microservice.grpc.nodejs_food_channel_processor.channel_order_food_report";

export interface Empty {
}

export interface BaseEmptyResponse {
  status: number;
  message: string;
  data: Empty | undefined;
}

export interface ChannelOrderHistoryRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  food_channel_id: number;
  from_date: string;
  to_date: string;
}

export interface ChannelOrderHistoryResponse {
  id: number;
  order_id: string;
  channel_branch_id: string;
  total_amount: number;
  channel_order_food_id: number;
  channel_order_food_name: string;
  channel_order_food_code: string;
  order_created_at: string;
  display_id: string;
  is_completed: number;
}

export interface ChannelOrderHistoryOutputResponse {
  list: ChannelOrderHistoryResponse[];
  total_order_completed: number;
  total_order_cancelled: number;
  total_revenue: number;
  total_revenue_SHF: number;
  total_revenue_GRF: number;
  total_revenue_GOF: number;
  total_revenue_BEF: number;
}

export interface ChannelOrderHistoryBaseResponse {
  status: number;
  message: string;
  data: ChannelOrderHistoryOutputResponse | undefined;
}

export interface ChannelFoodRevenueSumaryReportRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  food_channel_id: number;
  hour_to_take_report: number;
  group_type: number;
  from_date: string;
  to_date: string;
}

export interface ChannelFoodRevenueSumaryResponse {
  report_date: string;
  total_order_SHF: number;
  total_order_GRF: number;
  total_order_GOF: number;
  total_order_BEF: number;
  commission_amount_SHF: number;
  commission_amount_GRF: number;
  commission_amount_GOF: number;
  commission_amount_BEF: number;
  order_amount_SHF: number;
  order_amount_GRF: number;
  order_amount_GOF: number;
  order_amount_BEF: number;
  total_amount_SHF: number;
  total_amount_GRF: number;
  total_amount_GOF: number;
  total_amount_BEF: number;
}

export interface ChannelFoodRevenueSumaryOutputResponse {
  list: ChannelFoodRevenueSumaryResponse[];
  total_order: number;
  total_order_SHF: number;
  total_order_GRF: number;
  total_order_GOF: number;
  total_order_BEF: number;
  total_revenue: number;
  total_revenue_SHF: number;
  total_revenue_GRF: number;
  total_revenue_GOF: number;
  total_revenue_BEF: number;
  percent_SHF: number;
  percent_GRF: number;
  percent_GOF: number;
  percent_BEF: number;
}

export interface ChannelFoodRevenueSumaryBaseResponse {
  status: number;
  message: string;
  data: ChannelFoodRevenueSumaryOutputResponse | undefined;
}

export interface CustomerChannelFoodInformationReportRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_ids: string;
  channel_order_food_id: number;
  from_date_string: string;
  to_date_string: string;
  key_search: string;
  limit: number;
  offset: number;
}

export interface CustomerChannelFoodInformationReportResponse {
  id: number;
  customer_name: string;
  customer_phone: string;
  customer_address: string;
  total_order: number;
  total_order_SHF: number;
  total_order_GRF: number;
  total_order_GOF: number;
  total_order_BEF: number;
  total_order_amount_SHF: number;
  total_order_amount_BEF: number;
  total_order_amount_GRF: number;
  total_order_amount: number;
  total_amount_avg_SHF: number;
  total_amount_avg_GRF: number;
  total_amount_avg_BEF: number;
  total_amount_avg: number;
}

export interface CustomerChannelFoodInformationReportOutputResponse {
  list: CustomerChannelFoodInformationReportResponse[];
  total_customer_buy_once: number;
  total_customer_buy_two: number;
  total_customer_buy_three: number;
  total_customer_buy_much: number;
  total_record: number;
  total_order: number;
  total_order_SHF: number;
  total_order_GRF: number;
  total_order_GOF: number;
  total_order_BEF: number;
  limit: number;
  total_order_amount_SHF: number;
  total_order_amount_BEF: number;
  total_order_amount_GRF: number;
  total_order_amount: number;
}

export interface CustomerChannelFoodInformationReportBaseResponse {
  status: number;
  message: string;
  data: CustomerChannelFoodInformationReportOutputResponse | undefined;
}

export interface GetChannelFoodReportRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  hour_to_take_report: number;
  from_date_string: string;
  to_date_string: string;
  key_search: string;
  limit: number;
  offset: number;
}

export interface ChannelFoodReportResponse {
  food_name: string;
  total_quantity: number;
  shf_quantity: number;
  grf_quantity: number;
  bef_quantity: number;
}

export interface BaseListChannelFoodReportResponse {
  list: ChannelFoodReportResponse[];
  limit: number;
  total_record: number;
}

export interface ChannelFoodReportResultResponse {
  status: number;
  message: string;
  data: BaseListChannelFoodReportResponse | undefined;
}

export interface ChannelFoodRevenueSumaryDataReportRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  food_channel_id: number;
  hour_to_take_report: number;
  group_type: number;
  from_date: string;
  to_date: string;
}

export interface ChannelFoodSumaryDataReportResponse {
  commission_amount_SHF: number;
  commission_amount_GRF: number;
  commission_amount_BEF: number;
  total_commission_amount: number;
  order_amount_SHF: number;
  order_amount_GRF: number;
  order_amount_BEF: number;
  total_order_amount: number;
  total_amount_SHF: number;
  total_amount_GRF: number;
  total_amount_BEF: number;
  total_revenue_amount: number;
  discount_amount_SHF: number;
  discount_amount_GRF: number;
  discount_amount_BEF: number;
  total_discount_amount: number;
}

export interface ChannelFoodReportSumaryDataResultResponse {
  status: number;
  message: string;
  data: ChannelFoodSumaryDataReportResponse | undefined;
}

export interface ChannelFoodRevenueOrderReportRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  channel_order_food_id: number;
  hour_to_take_report: number;
  from_date: string;
  to_date: string;
  offset: number;
  limit: number;
  key_search: string;
}

export interface ChannelFoodOrderReportResponse {
  id: number;
  order_id: string;
  display_id: string;
  customer_name: string;
  customer_phone: string;
  order_amount: number;
  commission_amount: number;
  customer_discount_amount: number;
  total_amount: number;
}

export interface BaseListChannelFoodOrderReportResponse {
  list: ChannelFoodOrderReportResponse[];
  limit: number;
  total_record: number;
}

export interface ChannelFoodOrderReportResultResponse {
  status: number;
  message: string;
  data: BaseListChannelFoodOrderReportResponse | undefined;
}

/** ---------------------- getEarningSumaryReport ------------------------ */
export interface GetEarningSumaryReportRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  channel_branch_id: string;
  from_date: string;
  to_date: string;
}

export interface EarningSumaryReportResponse {
  net_sales: number;
  net_total: number;
  total_orders: number;
  breakdown_by_category: string;
}

export interface EarningSumaryReportResultResponse {
  status: number;
  message: string;
  data: EarningSumaryReportResponse | undefined;
}

export const VN_TECHRES_MICROSERVICE_GRPC_NODEJS_FOOD_CHANNEL_PROCESSOR_CHANNEL_ORDER_FOOD_REPORT_PACKAGE_NAME =
  "vn.techres.microservice.grpc.nodejs_food_channel_processor.channel_order_food_report";

export interface ChannelOrderFoodReportServiceClient {
  getListChannelOrderHistory(
    request: ChannelOrderHistoryRequest,
    metadata?: Metadata,
  ): Observable<ChannelOrderHistoryBaseResponse>;

  getChannelFoodRevenueSumaryReport(
    request: ChannelFoodRevenueSumaryReportRequest,
    metadata?: Metadata,
  ): Observable<ChannelFoodRevenueSumaryBaseResponse>;

  getCustomerChannelFoodInformationReport(
    request: CustomerChannelFoodInformationReportRequest,
    metadata?: Metadata,
  ): Observable<CustomerChannelFoodInformationReportBaseResponse>;

  getChannelFoodReport(
    request: GetChannelFoodReportRequest,
    metadata?: Metadata,
  ): Observable<ChannelFoodReportResultResponse>;

  getChannelFoodSumaryDataReport(
    request: ChannelFoodRevenueSumaryDataReportRequest,
    metadata?: Metadata,
  ): Observable<ChannelFoodReportSumaryDataResultResponse>;

  getChannelFoodOrdersReport(
    request: ChannelFoodRevenueOrderReportRequest,
    metadata?: Metadata,
  ): Observable<ChannelFoodOrderReportResultResponse>;

  getEarningSumaryReport(
    request: GetEarningSumaryReportRequest,
    metadata?: Metadata,
  ): Observable<EarningSumaryReportResultResponse>;
}

export interface ChannelOrderFoodReportServiceController {
  getListChannelOrderHistory(
    request: ChannelOrderHistoryRequest,
    metadata?: Metadata,
  ):
    | Promise<ChannelOrderHistoryBaseResponse>
    | Observable<ChannelOrderHistoryBaseResponse>
    | ChannelOrderHistoryBaseResponse;

  getChannelFoodRevenueSumaryReport(
    request: ChannelFoodRevenueSumaryReportRequest,
    metadata?: Metadata,
  ):
    | Promise<ChannelFoodRevenueSumaryBaseResponse>
    | Observable<ChannelFoodRevenueSumaryBaseResponse>
    | ChannelFoodRevenueSumaryBaseResponse;

  getCustomerChannelFoodInformationReport(
    request: CustomerChannelFoodInformationReportRequest,
    metadata?: Metadata,
  ):
    | Promise<CustomerChannelFoodInformationReportBaseResponse>
    | Observable<CustomerChannelFoodInformationReportBaseResponse>
    | CustomerChannelFoodInformationReportBaseResponse;

  getChannelFoodReport(
    request: GetChannelFoodReportRequest,
    metadata?: Metadata,
  ):
    | Promise<ChannelFoodReportResultResponse>
    | Observable<ChannelFoodReportResultResponse>
    | ChannelFoodReportResultResponse;

  getChannelFoodSumaryDataReport(
    request: ChannelFoodRevenueSumaryDataReportRequest,
    metadata?: Metadata,
  ):
    | Promise<ChannelFoodReportSumaryDataResultResponse>
    | Observable<ChannelFoodReportSumaryDataResultResponse>
    | ChannelFoodReportSumaryDataResultResponse;

  getChannelFoodOrdersReport(
    request: ChannelFoodRevenueOrderReportRequest,
    metadata?: Metadata,
  ):
    | Promise<ChannelFoodOrderReportResultResponse>
    | Observable<ChannelFoodOrderReportResultResponse>
    | ChannelFoodOrderReportResultResponse;

  getEarningSumaryReport(
    request: GetEarningSumaryReportRequest,
    metadata?: Metadata,
  ):
    | Promise<EarningSumaryReportResultResponse>
    | Observable<EarningSumaryReportResultResponse>
    | EarningSumaryReportResultResponse;
}

export function ChannelOrderFoodReportServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getListChannelOrderHistory",
      "getChannelFoodRevenueSumaryReport",
      "getCustomerChannelFoodInformationReport",
      "getChannelFoodReport",
      "getChannelFoodSumaryDataReport",
      "getChannelFoodOrdersReport",
      "getEarningSumaryReport",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ChannelOrderFoodReportService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ChannelOrderFoodReportService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CHANNEL_ORDER_FOOD_REPORT_SERVICE_NAME = "ChannelOrderFoodReportService";
