export enum ChannelOrderFoodStatusEnum {
   SHOPEE_FOOD_STATUS_DELIVERING = 6,
   SHOPEE_FOOD_STATUS_COMPLETED = 7,
   SHOPEE_FOOD_STATUS_CANCELLED = 8,

   GRAB_FOOD_STATUS_DELIVERING = 'ORDER_EXECUTING',
   GRAB_FOOD_STATUS_COMPLETED = 'COMPLETED',
   GRAB_FOOD_STATUS_CANCELLED = 'CANCELLED_MAX',
   GRAB_FOOD_STATUS_FAILED = 'FAILED',
   GRAB_FOOD_STATUS_CUSTOMER_CANCELLED = 'CANCELLED',

   BE_FOOD_STATUS_DELIVERING = 1,
   BE_FOOD_STATUS_COMPLETED = 12,
   BE_FOOD_STATUS_CANCELLED = 9,

}


