// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               v3.5.1
// source: channel-order.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "vn.techres.microservice.grpc.nodejs_food_channel_processor.channel_order";

export interface Empty {
}

export interface BaseEmptyResponse {
  status: number;
  message: string;
  data: Empty | undefined;
}

export interface OrderDetailRequest {
  id: number;
  is_app_food: number;
}

export interface OrderDetail {
  id: number;
  customer_order_id: number;
  food_id: string;
  food_name: string;
  order_detail_parent_id: number;
  order_detail_combo_parent_id: number;
  customer_order_detail_addition_ids: string;
  customer_order_detail_combo_ids: string;
  customer_order_detail_combo: string;
  customer_order_detail_addition: string;
  quantity: number;
  price: number;
  total_price: number;
  is_addition: number;
  is_combo: number;
  note: string;
  total_price_addition: number;
  created_at: string;
  updated_at: string;
  food_options: string;
}

export interface Order {
  id: number;
  channel_order_id: string;
  channel_order_food_id: number;
  channel_branch_id: string;
  total_amount: number;
  driver_name: string;
  driver_avatar: string;
  channel_order_food_name: string;
  channel_order_food_code: string;
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  order_id: number;
  customer_id: number;
  table_id: number;
  area_id: number;
  table_name: string;
  customer_name: string;
  phone: string;
  address: string;
  note: string;
  payment_method: number;
  payment_status: number;
  customer_order_status: number;
  customer_order_type: number;
  created_at: string;
  updated_at: string;
  shipping_fee: number;
  tracking_url: string;
  shippe_name: string;
  shipper_phone: string;
  order_time: number;
  cancel_comment: string;
  restaurant_third_party_delivery_id: number;
  shipping_lat: string;
  shipping_lng: string;
  third_party_delivery_order_id: string;
  third_party_delivery_name: string;
  is_app_food: number;
  display_id: string;
  order_amount: number;
  discount_amount: number;
  customer_order_amount: number;
  customer_discount_amount: number;
  details: OrderDetail[];
  channel_order_code: string;
}

export interface OrderBaseResponse {
  status: number;
  message: string;
  data: Order | undefined;
}

export interface ListOrderBaseResponse {
  status: number;
  message: string;
  data: Order[];
}

export interface OrderRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  channel_order_food_id: number;
  customer_order_status: string;
  is_have_restaurant_order: number;
  is_app_food: number;
  is_active: number;
  is_connection_SHF: number;
  is_connection_GRF: number;
  is_connection_BEF: number;
  object_SHF: string;
  object_GRF: string;
  object_BEF: string;
}

export interface ResultBaseResponse {
  status: number;
  message: string;
  data: ResultResponse | undefined;
}

export interface ErrorResponse {
  code: string;
  message: string;
  channel_order_food_token_id: number;
}

export interface ResultResponse {
  errors: ErrorResponse[];
  list: Order[];
}

export interface SyncOrderRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  access_tokens: string;
  new_orders_SHF: string;
  new_orders_GRF: string;
  new_orders_BEF: string;
  history_orders_SHF: string;
  history_orders_GRF: string;
  history_orders_BEF: string;
  customers: string;
}

export interface SyncOrderMongoRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  channel_order_food_id: number;
  access_tokens: string;
}

export const VN_TECHRES_MICROSERVICE_GRPC_NODEJS_FOOD_CHANNEL_PROCESSOR_CHANNEL_ORDER_PACKAGE_NAME =
  "vn.techres.microservice.grpc.nodejs_food_channel_processor.channel_order";

export interface ChannelOrderServiceClient {
  getOrderDetail(request: OrderDetailRequest, metadata?: Metadata): Observable<OrderBaseResponse>;

  getOrders(request: OrderRequest, metadata?: Metadata): Observable<ResultBaseResponse>;

  syncOrders(request: SyncOrderRequest, metadata?: Metadata): Observable<BaseEmptyResponse>;

  syncOrdersMongo(request: SyncOrderMongoRequest, metadata?: Metadata): Observable<BaseEmptyResponse>;
}

export interface ChannelOrderServiceController {
  getOrderDetail(
    request: OrderDetailRequest,
    metadata?: Metadata,
  ): Promise<OrderBaseResponse> | Observable<OrderBaseResponse> | OrderBaseResponse;

  getOrders(
    request: OrderRequest,
    metadata?: Metadata,
  ): Promise<ResultBaseResponse> | Observable<ResultBaseResponse> | ResultBaseResponse;

  syncOrders(
    request: SyncOrderRequest,
    metadata?: Metadata,
  ): Promise<BaseEmptyResponse> | Observable<BaseEmptyResponse> | BaseEmptyResponse;

  syncOrdersMongo(
    request: SyncOrderMongoRequest,
    metadata?: Metadata,
  ): Promise<BaseEmptyResponse> | Observable<BaseEmptyResponse> | BaseEmptyResponse;
}

export function ChannelOrderServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getOrderDetail", "getOrders", "syncOrders", "syncOrdersMongo"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ChannelOrderService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ChannelOrderService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CHANNEL_ORDER_SERVICE_NAME = "ChannelOrderService";
