// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               v3.5.1
// source: channel-order-food.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "vn.techres.microservice.grpc.nodejs_food_channel_processor.channel_order_food";

export interface ChannelOrderFoodByIdRequest {
  id: number;
}

export interface ChannelOrderFoodResponse {
  id: number;
  name: string;
  code: string;
  image_url: string;
  status: number;
}

export interface BaseResponse {
  status: number;
  message: string;
  data: ChannelOrderFoodResponse | undefined;
}

export interface GetFoodsChannelOrderFoodRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  channel_order_food_id: number;
  channel_branch_id: string;
}

export interface FoodChannelOrderFoodResponse {
  id: string;
  name: string;
  price: string;
  picture_url: string;
  description: string;
  is_pending: number;
}

export interface ListFoodChannelOrderFoodResponse {
  status: number;
  message: string;
  data: FoodChannelOrderFoodResponse[];
}

export interface UpdateFoodPricesChannelOrderFoodRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  channel_order_food_id: number;
  channel_branch_id: string;
  foods: UpdateFoodPriceRequest[];
}

export interface UpdateFoodPriceRequest {
  id: string;
  price: string;
}

export interface Empty {
}

export interface BaseEmptyResponse {
  status: number;
  message: string;
  data: Empty | undefined;
}

export interface GetBranchsChannelOrderFoodRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  channel_order_food_id: number;
}

export interface BranchChannelOrderFoodResponse {
  branch_id: string;
  branch_name: string;
}

export interface ListBranchChannelOrderFoodResponse {
  status: number;
  message: string;
  data: BranchChannelOrderFoodResponse[];
}

export interface AssignChannelBranchRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  channel_order_food_id: number;
  branch_maps: string;
}

export interface GetDetailBillAppFoodRequest {
  channel_order_food_id: number;
  channel_order_food_code: string;
}

export interface BillAppFoodBaseResponse {
  status: number;
  message: string;
  data: DetailBillAppFoodResponse[];
}

export interface DetailBillAppFoodResponse {
  food_id: string;
  food_name: string;
  food_note: string;
}

/** --------- GetList -------------- */
export interface ChannelOrderFoodRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  channel_order_food_id: number;
  is_connect: number;
  key_search: string;
}

export interface ListBaseResponse {
  status: number;
  message: string;
  data: ChannelOrderFood[];
}

export interface ChannelOrderFood {
  id: number;
  name: string;
  code: string;
  image_url: string;
  status: number;
  restaurant_brand_channel_order_food_map_id: number;
  is_connect: number;
  channel_order_food_token_id: number;
}

export interface OrderRefreshRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  channel_orders: string;
}

export interface AssignMultipleChannelBranchRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  channel_order_food_id: number;
  branch_maps: string;
}

export interface GetChannelBranchesOfTokenToConnectionRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  channel_order_food_id: number;
}

export interface ChannelBranchesOfTokenToConnectionResponse {
  branch_id: string;
  branch_name: string;
  channel_order_food_token_id: number;
  channel_order_food_token_name: string;
  branch_address: string;
  branch_phone: string;
}

export interface ListChannelBranchesOfTokenToConnectionResponse {
  status: number;
  message: string;
  data: ChannelBranchesOfTokenToConnectionResponse[];
}

export interface GetFoodToppingRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  channel_order_food_id: number;
  channel_branch_id: string;
}

export interface GroupFoodToppingResponse {
  id: string;
  name: string;
  list: FoodToppingResponse[];
}

export interface FoodToppingResponse {
  id: string;
  name: string;
  price: string;
}

export interface ListFoodToppingResponse {
  status: number;
  message: string;
  data: GroupFoodToppingResponse[];
}

export interface ComfirmChannelOrderRequest {
  restaurant_id: number;
  channel_order_id: number;
}

export interface SyncChannelBranchRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  channel_order_food_id: number;
}

/** ---------- deleteRedisFoodChannelFoodTechresMap ----------------- */
export interface DeleteRedisFoodChannelFoodTechresMapRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  channel_order_food_id: number;
}

export const VN_TECHRES_MICROSERVICE_GRPC_NODEJS_FOOD_CHANNEL_PROCESSOR_CHANNEL_ORDER_FOOD_PACKAGE_NAME =
  "vn.techres.microservice.grpc.nodejs_food_channel_processor.channel_order_food";

export interface ChannelOrderFoodServiceClient {
  findById(request: ChannelOrderFoodByIdRequest, metadata?: Metadata): Observable<BaseResponse>;

  getFoodsChannelOrderFood(
    request: GetFoodsChannelOrderFoodRequest,
    metadata?: Metadata,
  ): Observable<ListFoodChannelOrderFoodResponse>;

  updateFoodPrices(
    request: UpdateFoodPricesChannelOrderFoodRequest,
    metadata?: Metadata,
  ): Observable<BaseEmptyResponse>;

  getBranchesChannelOrderFood(
    request: GetBranchsChannelOrderFoodRequest,
    metadata?: Metadata,
  ): Observable<ListBranchChannelOrderFoodResponse>;

  syncAssignBranch(request: AssignChannelBranchRequest, metadata?: Metadata): Observable<BaseEmptyResponse>;

  getDetailBillAppFood(request: GetDetailBillAppFoodRequest, metadata?: Metadata): Observable<BillAppFoodBaseResponse>;

  getList(request: ChannelOrderFoodRequest, metadata?: Metadata): Observable<ListBaseResponse>;

  orderRefresh(request: OrderRefreshRequest, metadata?: Metadata): Observable<BaseEmptyResponse>;

  syncAssignMultipleChannelBranch(
    request: AssignMultipleChannelBranchRequest,
    metadata?: Metadata,
  ): Observable<BaseEmptyResponse>;

  getChannelBranchesOfTokenToConnection(
    request: GetChannelBranchesOfTokenToConnectionRequest,
    metadata?: Metadata,
  ): Observable<ListChannelBranchesOfTokenToConnectionResponse>;

  getFoodToppings(request: GetFoodToppingRequest, metadata?: Metadata): Observable<ListFoodToppingResponse>;

  comfirmChannelOrder(request: ComfirmChannelOrderRequest, metadata?: Metadata): Observable<BaseEmptyResponse>;

  syncBranches(
    request: SyncChannelBranchRequest,
    metadata?: Metadata,
  ): Observable<ListChannelBranchesOfTokenToConnectionResponse>;

  deleteRedisFoodChannelFoodTechresMap(
    request: DeleteRedisFoodChannelFoodTechresMapRequest,
    metadata?: Metadata,
  ): Observable<BaseEmptyResponse>;
}

export interface ChannelOrderFoodServiceController {
  findById(
    request: ChannelOrderFoodByIdRequest,
    metadata?: Metadata,
  ): Promise<BaseResponse> | Observable<BaseResponse> | BaseResponse;

  getFoodsChannelOrderFood(
    request: GetFoodsChannelOrderFoodRequest,
    metadata?: Metadata,
  ):
    | Promise<ListFoodChannelOrderFoodResponse>
    | Observable<ListFoodChannelOrderFoodResponse>
    | ListFoodChannelOrderFoodResponse;

  updateFoodPrices(
    request: UpdateFoodPricesChannelOrderFoodRequest,
    metadata?: Metadata,
  ): Promise<BaseEmptyResponse> | Observable<BaseEmptyResponse> | BaseEmptyResponse;

  getBranchesChannelOrderFood(
    request: GetBranchsChannelOrderFoodRequest,
    metadata?: Metadata,
  ):
    | Promise<ListBranchChannelOrderFoodResponse>
    | Observable<ListBranchChannelOrderFoodResponse>
    | ListBranchChannelOrderFoodResponse;

  syncAssignBranch(
    request: AssignChannelBranchRequest,
    metadata?: Metadata,
  ): Promise<BaseEmptyResponse> | Observable<BaseEmptyResponse> | BaseEmptyResponse;

  getDetailBillAppFood(
    request: GetDetailBillAppFoodRequest,
    metadata?: Metadata,
  ): Promise<BillAppFoodBaseResponse> | Observable<BillAppFoodBaseResponse> | BillAppFoodBaseResponse;

  getList(
    request: ChannelOrderFoodRequest,
    metadata?: Metadata,
  ): Promise<ListBaseResponse> | Observable<ListBaseResponse> | ListBaseResponse;

  orderRefresh(
    request: OrderRefreshRequest,
    metadata?: Metadata,
  ): Promise<BaseEmptyResponse> | Observable<BaseEmptyResponse> | BaseEmptyResponse;

  syncAssignMultipleChannelBranch(
    request: AssignMultipleChannelBranchRequest,
    metadata?: Metadata,
  ): Promise<BaseEmptyResponse> | Observable<BaseEmptyResponse> | BaseEmptyResponse;

  getChannelBranchesOfTokenToConnection(
    request: GetChannelBranchesOfTokenToConnectionRequest,
    metadata?: Metadata,
  ):
    | Promise<ListChannelBranchesOfTokenToConnectionResponse>
    | Observable<ListChannelBranchesOfTokenToConnectionResponse>
    | ListChannelBranchesOfTokenToConnectionResponse;

  getFoodToppings(
    request: GetFoodToppingRequest,
    metadata?: Metadata,
  ): Promise<ListFoodToppingResponse> | Observable<ListFoodToppingResponse> | ListFoodToppingResponse;

  comfirmChannelOrder(
    request: ComfirmChannelOrderRequest,
    metadata?: Metadata,
  ): Promise<BaseEmptyResponse> | Observable<BaseEmptyResponse> | BaseEmptyResponse;

  syncBranches(
    request: SyncChannelBranchRequest,
    metadata?: Metadata,
  ):
    | Promise<ListChannelBranchesOfTokenToConnectionResponse>
    | Observable<ListChannelBranchesOfTokenToConnectionResponse>
    | ListChannelBranchesOfTokenToConnectionResponse;

  deleteRedisFoodChannelFoodTechresMap(
    request: DeleteRedisFoodChannelFoodTechresMapRequest,
    metadata?: Metadata,
  ): Promise<BaseEmptyResponse> | Observable<BaseEmptyResponse> | BaseEmptyResponse;
}

export function ChannelOrderFoodServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "findById",
      "getFoodsChannelOrderFood",
      "updateFoodPrices",
      "getBranchesChannelOrderFood",
      "syncAssignBranch",
      "getDetailBillAppFood",
      "getList",
      "orderRefresh",
      "syncAssignMultipleChannelBranch",
      "getChannelBranchesOfTokenToConnection",
      "getFoodToppings",
      "comfirmChannelOrder",
      "syncBranches",
      "deleteRedisFoodChannelFoodTechresMap",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ChannelOrderFoodService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ChannelOrderFoodService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CHANNEL_ORDER_FOOD_SERVICE_NAME = "ChannelOrderFoodService";
