// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               v3.5.1
// source: food-channel-validator.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "vn.techres.microservice.grpc.nodejs_food_channel_validator.check_token";

export interface Empty {
}

export interface FoodChannelValidatorDTO {
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
}

export interface BaseResponse {
  status: number;
  message: string;
  data: Empty | undefined;
}

export interface DataResponse {
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  is_active: number;
  tokens: Object[];
  is_use_kafka: number;
}

export interface Object {
  channel_order_food_id: number;
  channel_order_food_token_id: number;
  channel_order_food_token_name: string;
  access_token: string;
  username: string;
  password: string;
  x_merchant_token: string;
  device_id: string;
  device_brand: string;
  channel_branch_id: string;
  merchant_id: string;
  url_get_new_orders: string;
  url_get_history_orders: string;
  url_get_order_detail: string;
  url_login: string;
  url_update_device: string;
  branch_id: number;
}

export interface BaseDataResponse {
  status: number;
  message: string;
  data: DataResponse | undefined;
}

export const VN_TECHRES_MICROSERVICE_GRPC_NODEJS_FOOD_CHANNEL_VALIDATOR_CHECK_TOKEN_PACKAGE_NAME =
  "vn.techres.microservice.grpc.nodejs_food_channel_validator.check_token";

export interface FoodChannelValidatorServiceClient {
  checkFoodChannelValidatorRedis(request: FoodChannelValidatorDTO, metadata?: Metadata): Observable<BaseDataResponse>;
}

export interface FoodChannelValidatorServiceController {
  checkFoodChannelValidatorRedis(
    request: FoodChannelValidatorDTO,
    metadata?: Metadata,
  ): Promise<BaseDataResponse> | Observable<BaseDataResponse> | BaseDataResponse;
}

export function FoodChannelValidatorServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["checkFoodChannelValidatorRedis"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("FoodChannelValidatorService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("FoodChannelValidatorService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const FOOD_CHANNEL_VALIDATOR_SERVICE_NAME = "FoodChannelValidatorService";
