// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               v3.5.1
// source: channel-order.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "vn.techres.microservice.grpc.nodejs_food_channel_processor.channel_order";

export interface Empty {
}

export interface BaseEmptyResponse {
  status: number;
  message: string;
  data: Empty | undefined;
}

export interface OrderDetailRequest {
  id: number;
  is_app_food: number;
  restaurant_id: number;
}

export interface OrderDetail {
  id: number;
  customer_order_id: number;
  food_id: string;
  food_name: string;
  order_detail_parent_id: number;
  order_detail_combo_parent_id: number;
  customer_order_detail_addition_ids: string;
  customer_order_detail_combo_ids: string;
  customer_order_detail_combo: string;
  customer_order_detail_addition: string;
  quantity: number;
  price: number;
  total_price: number;
  is_addition: number;
  is_combo: number;
  note: string;
  total_price_addition: number;
  created_at: string;
  updated_at: string;
  food_options: string;
  is_allow_print_stamp: number;
  restaurant_kitchen_place_id: number;
}

export interface Order {
  id: number;
  channel_order_id: string;
  channel_order_food_id: number;
  channel_branch_id: string;
  total_amount: number;
  driver_name: string;
  driver_avatar: string;
  channel_order_food_name: string;
  channel_order_food_code: string;
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  order_id: number;
  customer_id: number;
  table_id: number;
  area_id: number;
  table_name: string;
  customer_name: string;
  phone: string;
  address: string;
  note: string;
  payment_method: number;
  payment_status: number;
  customer_order_status: number;
  customer_order_type: number;
  created_at: string;
  updated_at: string;
  shipping_fee: number;
  tracking_url: string;
  shippe_name: string;
  shipper_phone: string;
  order_time: number;
  cancel_comment: string;
  restaurant_third_party_delivery_id: number;
  shipping_lat: string;
  shipping_lng: string;
  third_party_delivery_order_id: string;
  third_party_delivery_name: string;
  is_app_food: number;
  display_id: string;
  order_amount: number;
  discount_amount: number;
  customer_order_amount: number;
  customer_discount_amount: number;
  details: OrderDetail[];
  channel_order_code: string;
  driver_phone: string;
  channel_branch_name: string;
  channel_branch_address: string;
  channel_branch_phone: string;
  item_discount_amount: number;
  deliver_time: string;
  is_scheduled_order: number;
  is_printed: number;
  is_cancel_printed: number;
  is_cancel_order: number;
}

export interface OrderBaseResponse {
  status: number;
  message: string;
  data: Order | undefined;
}

export interface ListOrderBaseResponse {
  status: number;
  message: string;
  data: Order[];
}

export interface OrderRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  channel_order_food_id: number;
  customer_order_status: string;
  is_have_restaurant_order: number;
  is_app_food: number;
  is_active: number;
  tokens: string;
  is_use_kafka: number;
}

export interface ResultBaseResponse {
  status: number;
  message: string;
  data: ResultResponse | undefined;
}

export interface ErrorResponse {
  code: string;
  message: string;
  token_name: string;
  token_username: string;
}

export interface ResultResponse {
  errors: ErrorResponse[];
  list: Order[];
}

export interface ResultV3BaseResponse {
  status: number;
  message: string;
  data: ResultV3Response | undefined;
}

export interface ResultV3Response {
  errors: ErrorResponse[];
  list: Order[];
  is_new_order_app_food: number;
  is_new_order_online: number;
}

export interface SyncOrderRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  access_tokens: string;
  new_orders_SHF: string;
  new_orders_GRF: string;
  new_orders_BEF: string;
  history_orders_SHF: string;
  history_orders_GRF: string;
  history_orders_BEF: string;
  customers: string;
}

export interface SyncChannelOrderHistoryRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  tokens: string;
}

/** ---------- resetChannelOrder --------------- */
export interface ResetChannelOrderRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  channel_order_food_id: number;
}

export interface SyncOrderMongoRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  channel_order_food_id: number;
  access_tokens: string;
}

/** ---------- handleCompleteChannelOrder --------------- */
export interface HandleCompleteChannelOrderRequest {
  restaurant_id: number;
  id: number;
}

/** ---------- handleCancelChannelOrder --------------- */
export interface HandleCancelChannelOrderRequest {
  restaurant_id: number;
  id: number;
}

/** ---------- batchConfirmChannelOrder --------------- */
export interface BatchConfirmChannelOrderRequest {
  restaurant_id: number;
  branch_id: number;
  ids: string;
}

export interface BatchConfirmChannelOrderResponseResultResponse {
  status: number;
  message: string;
  data: string;
}

/** ---------- updateCancelPrintOrders --------------- */
export interface UpdateCancelPrintOrdersRequest {
  restaurant_id: number;
  branch_id: number;
  ids: string;
}

export interface OrderDetailToPrintRequest {
  id: number;
  restaurant_id: number;
}

/** ---------- handleCompleteChannelOrderV2 --------------- */
export interface HandleCompleteChannelOrderV2Request {
  restaurant_id: number;
  id: number;
  restaurant_order_id: number;
}

/** ---------- handleCancelChannelOrderv2 --------------- */
export interface HandleCancelChannelOrderV2Request {
  restaurant_id: number;
  id: number;
  restaurant_order_id: number;
}

export const VN_TECHRES_MICROSERVICE_GRPC_NODEJS_FOOD_CHANNEL_PROCESSOR_CHANNEL_ORDER_PACKAGE_NAME =
  "vn.techres.microservice.grpc.nodejs_food_channel_processor.channel_order";

export interface ChannelOrderServiceClient {
  getOrderDetail(request: OrderDetailRequest, metadata?: Metadata): Observable<OrderBaseResponse>;

  getOrderDetailV2(request: OrderDetailRequest, metadata?: Metadata): Observable<OrderBaseResponse>;

  getOrders(request: OrderRequest, metadata?: Metadata): Observable<ResultBaseResponse>;

  getOrdersV2(request: OrderRequest, metadata?: Metadata): Observable<ResultBaseResponse>;

  getOrdersV3(request: OrderRequest, metadata?: Metadata): Observable<ResultV3BaseResponse>;

  getOrdersV4(request: OrderRequest, metadata?: Metadata): Observable<ResultV3BaseResponse>;

  syncOrders(request: SyncOrderRequest, metadata?: Metadata): Observable<BaseEmptyResponse>;

  syncChannelOrderHistory(request: SyncChannelOrderHistoryRequest, metadata?: Metadata): Observable<BaseEmptyResponse>;

  resetChannelOrder(request: ResetChannelOrderRequest, metadata?: Metadata): Observable<BaseEmptyResponse>;

  handleCompleteChannelOrder(
    request: HandleCompleteChannelOrderRequest,
    metadata?: Metadata,
  ): Observable<BaseEmptyResponse>;

  handleCancelChannelOrder(
    request: HandleCancelChannelOrderRequest,
    metadata?: Metadata,
  ): Observable<BaseEmptyResponse>;

  syncOrdersMongo(request: SyncOrderMongoRequest, metadata?: Metadata): Observable<BaseEmptyResponse>;

  batchConfirmChannelOrder(
    request: BatchConfirmChannelOrderRequest,
    metadata?: Metadata,
  ): Observable<BatchConfirmChannelOrderResponseResultResponse>;

  updateCancelPrintOrders(request: UpdateCancelPrintOrdersRequest, metadata?: Metadata): Observable<BaseEmptyResponse>;

  getOrderDetailToPrint(request: OrderDetailToPrintRequest, metadata?: Metadata): Observable<OrderBaseResponse>;

  handleCompleteChannelOrderV2(
    request: HandleCompleteChannelOrderV2Request,
    metadata?: Metadata,
  ): Observable<BaseEmptyResponse>;

  handleCancelChannelOrderV2(
    request: HandleCancelChannelOrderV2Request,
    metadata?: Metadata,
  ): Observable<BaseEmptyResponse>;

  batchConfirmChannelOrderV2(
    request: BatchConfirmChannelOrderRequest,
    metadata?: Metadata,
  ): Observable<BatchConfirmChannelOrderResponseResultResponse>;

  updateCancelPrintOrdersV2(
    request: UpdateCancelPrintOrdersRequest,
    metadata?: Metadata,
  ): Observable<BaseEmptyResponse>;

  getOrderDetailToPrintV2(request: OrderDetailToPrintRequest, metadata?: Metadata): Observable<OrderBaseResponse>;

  batchConfirmChannelOrderV3(
    request: BatchConfirmChannelOrderRequest,
    metadata?: Metadata,
  ): Observable<BaseEmptyResponse>;

  handleCancelChannelOrderV3(
    request: HandleCancelChannelOrderV2Request,
    metadata?: Metadata,
  ): Observable<BaseEmptyResponse>;

  handleCompleteChannelOrderV3(
    request: HandleCompleteChannelOrderV2Request,
    metadata?: Metadata,
  ): Observable<BaseEmptyResponse>;
}

export interface ChannelOrderServiceController {
  getOrderDetail(
    request: OrderDetailRequest,
    metadata?: Metadata,
  ): Promise<OrderBaseResponse> | Observable<OrderBaseResponse> | OrderBaseResponse;

  getOrderDetailV2(
    request: OrderDetailRequest,
    metadata?: Metadata,
  ): Promise<OrderBaseResponse> | Observable<OrderBaseResponse> | OrderBaseResponse;

  getOrders(
    request: OrderRequest,
    metadata?: Metadata,
  ): Promise<ResultBaseResponse> | Observable<ResultBaseResponse> | ResultBaseResponse;

  getOrdersV2(
    request: OrderRequest,
    metadata?: Metadata,
  ): Promise<ResultBaseResponse> | Observable<ResultBaseResponse> | ResultBaseResponse;

  getOrdersV3(
    request: OrderRequest,
    metadata?: Metadata,
  ): Promise<ResultV3BaseResponse> | Observable<ResultV3BaseResponse> | ResultV3BaseResponse;

  getOrdersV4(
    request: OrderRequest,
    metadata?: Metadata,
  ): Promise<ResultV3BaseResponse> | Observable<ResultV3BaseResponse> | ResultV3BaseResponse;

  syncOrders(
    request: SyncOrderRequest,
    metadata?: Metadata,
  ): Promise<BaseEmptyResponse> | Observable<BaseEmptyResponse> | BaseEmptyResponse;

  syncChannelOrderHistory(
    request: SyncChannelOrderHistoryRequest,
    metadata?: Metadata,
  ): Promise<BaseEmptyResponse> | Observable<BaseEmptyResponse> | BaseEmptyResponse;

  resetChannelOrder(
    request: ResetChannelOrderRequest,
    metadata?: Metadata,
  ): Promise<BaseEmptyResponse> | Observable<BaseEmptyResponse> | BaseEmptyResponse;

  handleCompleteChannelOrder(
    request: HandleCompleteChannelOrderRequest,
    metadata?: Metadata,
  ): Promise<BaseEmptyResponse> | Observable<BaseEmptyResponse> | BaseEmptyResponse;

  handleCancelChannelOrder(
    request: HandleCancelChannelOrderRequest,
    metadata?: Metadata,
  ): Promise<BaseEmptyResponse> | Observable<BaseEmptyResponse> | BaseEmptyResponse;

  syncOrdersMongo(
    request: SyncOrderMongoRequest,
    metadata?: Metadata,
  ): Promise<BaseEmptyResponse> | Observable<BaseEmptyResponse> | BaseEmptyResponse;

  batchConfirmChannelOrder(
    request: BatchConfirmChannelOrderRequest,
    metadata?: Metadata,
  ):
    | Promise<BatchConfirmChannelOrderResponseResultResponse>
    | Observable<BatchConfirmChannelOrderResponseResultResponse>
    | BatchConfirmChannelOrderResponseResultResponse;

  updateCancelPrintOrders(
    request: UpdateCancelPrintOrdersRequest,
    metadata?: Metadata,
  ): Promise<BaseEmptyResponse> | Observable<BaseEmptyResponse> | BaseEmptyResponse;

  getOrderDetailToPrint(
    request: OrderDetailToPrintRequest,
    metadata?: Metadata,
  ): Promise<OrderBaseResponse> | Observable<OrderBaseResponse> | OrderBaseResponse;

  handleCompleteChannelOrderV2(
    request: HandleCompleteChannelOrderV2Request,
    metadata?: Metadata,
  ): Promise<BaseEmptyResponse> | Observable<BaseEmptyResponse> | BaseEmptyResponse;

  handleCancelChannelOrderV2(
    request: HandleCancelChannelOrderV2Request,
    metadata?: Metadata,
  ): Promise<BaseEmptyResponse> | Observable<BaseEmptyResponse> | BaseEmptyResponse;

  batchConfirmChannelOrderV2(
    request: BatchConfirmChannelOrderRequest,
    metadata?: Metadata,
  ):
    | Promise<BatchConfirmChannelOrderResponseResultResponse>
    | Observable<BatchConfirmChannelOrderResponseResultResponse>
    | BatchConfirmChannelOrderResponseResultResponse;

  updateCancelPrintOrdersV2(
    request: UpdateCancelPrintOrdersRequest,
    metadata?: Metadata,
  ): Promise<BaseEmptyResponse> | Observable<BaseEmptyResponse> | BaseEmptyResponse;

  getOrderDetailToPrintV2(
    request: OrderDetailToPrintRequest,
    metadata?: Metadata,
  ): Promise<OrderBaseResponse> | Observable<OrderBaseResponse> | OrderBaseResponse;

  batchConfirmChannelOrderV3(
    request: BatchConfirmChannelOrderRequest,
    metadata?: Metadata,
  ): Promise<BaseEmptyResponse> | Observable<BaseEmptyResponse> | BaseEmptyResponse;

  handleCancelChannelOrderV3(
    request: HandleCancelChannelOrderV2Request,
    metadata?: Metadata,
  ): Promise<BaseEmptyResponse> | Observable<BaseEmptyResponse> | BaseEmptyResponse;

  handleCompleteChannelOrderV3(
    request: HandleCompleteChannelOrderV2Request,
    metadata?: Metadata,
  ): Promise<BaseEmptyResponse> | Observable<BaseEmptyResponse> | BaseEmptyResponse;
}

export function ChannelOrderServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getOrderDetail",
      "getOrderDetailV2",
      "getOrders",
      "getOrdersV2",
      "getOrdersV3",
      "getOrdersV4",
      "syncOrders",
      "syncChannelOrderHistory",
      "resetChannelOrder",
      "handleCompleteChannelOrder",
      "handleCancelChannelOrder",
      "syncOrdersMongo",
      "batchConfirmChannelOrder",
      "updateCancelPrintOrders",
      "getOrderDetailToPrint",
      "handleCompleteChannelOrderV2",
      "handleCancelChannelOrderV2",
      "batchConfirmChannelOrderV2",
      "updateCancelPrintOrdersV2",
      "getOrderDetailToPrintV2",
      "batchConfirmChannelOrderV3",
      "handleCancelChannelOrderV3",
      "handleCompleteChannelOrderV3",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ChannelOrderService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ChannelOrderService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CHANNEL_ORDER_SERVICE_NAME = "ChannelOrderService";
