// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               v3.5.1
// source: branch-channel-food-commission-percent-map.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage =
  "vn.techres.microservice.grpc.nodejs_food_channel_processor.branch_channel_food_commission_percent_map";

export interface BaseResponse {
  status: number;
  message: string;
  data: BranchChannelFoodCommissionPercentMap | undefined;
}

export interface SettingCommissionPercentDTO {
  id: number;
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  channel_order_food_id: number;
  percent: number;
  channel_order_food_token_id: number;
}

export interface BranchChannelFoodCommissionPercentMap {
  id: number;
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  channel_order_food_id: number;
  channel_order_food_token_id: number;
  channel_branch_id: string;
  percent: number;
}

/** ---------- getListCommissionPercentSettingV2 --------------- */
export interface GetListCommissionPercentSettingV2DTO {
  restaurant_id: number;
  restaurant_brand_id: number;
  branch_id: number;
  channel_order_food_id: number;
  channel_order_food_token_id: number;
}

export interface CommissionPercentSettingV2DataResponse {
  id: number;
  channel_order_food_id: number;
  channel_order_food_token_id: number;
  channel_order_food_token_name: string;
  percent: number;
  username: string;
}

export interface ListV2BaseResponse {
  status: number;
  message: string;
  data: CommissionPercentSettingV2DataResponse[];
}

export const VN_TECHRES_MICROSERVICE_GRPC_NODEJS_FOOD_CHANNEL_PROCESSOR_BRANCH_CHANNEL_FOOD_COMMISSION_PERCENT_MAP_PACKAGE_NAME =
  "vn.techres.microservice.grpc.nodejs_food_channel_processor.branch_channel_food_commission_percent_map";

export interface SettingCommissionServiceClient {
  updateSettingCommissionPercent(request: SettingCommissionPercentDTO, metadata?: Metadata): Observable<BaseResponse>;

  getListCommissionPercentSettingV2(
    request: GetListCommissionPercentSettingV2DTO,
    metadata?: Metadata,
  ): Observable<ListV2BaseResponse>;
}

export interface SettingCommissionServiceController {
  updateSettingCommissionPercent(
    request: SettingCommissionPercentDTO,
    metadata?: Metadata,
  ): Promise<BaseResponse> | Observable<BaseResponse> | BaseResponse;

  getListCommissionPercentSettingV2(
    request: GetListCommissionPercentSettingV2DTO,
    metadata?: Metadata,
  ): Promise<ListV2BaseResponse> | Observable<ListV2BaseResponse> | ListV2BaseResponse;
}

export function SettingCommissionServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["updateSettingCommissionPercent", "getListCommissionPercentSettingV2"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("SettingCommissionService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("SettingCommissionService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const SETTING_COMMISSION_SERVICE_NAME = "SettingCommissionService";
