// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.0
//   protoc               v3.5.1
// source: order-channel-order-food-server.proto

/* eslint-disable */
import { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "vn.techres.microservice.grpc.nodejs_order_channel_order_food";

export interface GetListOrderRequest {
  restaurant_id: number;
  restaurant_brand_id: number;
  channel_order_food_id: number;
  channel_branch_ids: string;
  key_search: string;
  limit: number;
  page: number;
  is_have_restaurant_order: number;
}

export interface OrderResponse {
  id: number;
  order_id: string;
  channel_order_food_id: number;
  channel_branch_id: string;
  total_amount: string;
  driver_name: string;
  driver_avatar: string;
  channel_order_food_name: string;
  channel_order_food_code: string;
  details: OrderDetailResponse[];
  display_id: string;
  discount_amount: string;
  restaurant_order_id: number;
  customer_order_amount: string;
  customer_discount_amount: string;
  order_amount: string;
  driver_phone: string;
  customer_name: string;
  phone: string;
  address: string;
  shipping_fee: string;
  create_at: string;
  channel_branch_name: string;
  channel_branch_address: string;
  channel_branch_phone: string;
  note: string;
  item_discount_amount: string;
  is_scheduled_order: number;
  deliver_time: string;
}

export interface ListOrderResponse {
  limit: number;
  total_record: number;
  list: OrderResponse[];
}

export interface ResultOrderResponse {
  status: number;
  message: string;
  data: ListOrderResponse | undefined;
}

export interface GetOrderDetailRequest {
  channel_order_id: number;
  channel_order_food_id: number;
  order_id: string;
}

export interface OrderDetailResponse {
  id: number;
  channel_order_id: number;
  order_id: string;
  channel_order_food_id: number;
  food_id: string;
  food_name: string;
  quantity: number;
  food_price: string;
  food_note: string;
  food_options: string;
  food_price_addition: string;
}

export interface ResultOrderDetailResponse {
  status: number;
  message: string;
  data: OrderResponse | undefined;
}

export interface updateOrderRequest {
  channel_order_id: number;
  restaurant_order_id: number;
}

export interface Empty {
}

export interface BaseResponse {
  status: number;
  message: string;
  data: Empty | undefined;
}

export interface GetDetailBillAppFoodRequest {
  channel_order_food_id: number;
  channel_order_food_code: string;
}

export interface BillAppFoodBaseResponse {
  status: number;
  message: string;
  data: DetailBillAppFoodResponse[];
}

export interface DetailBillAppFoodResponse {
  food_id: string;
  food_name: string;
  food_note: string;
}

export interface GetListChannelOrderRequest {
  restaurant_id: number;
  channel_order_ids: string;
}

export interface ResultChannelOrderResponse {
  status: number;
  message: string;
  data: OrderResponse[];
}

export interface UpdateOrderRequestV2 {
  restaurant_id: number;
  channel_order_update_json: string;
}

export const VN_TECHRES_MICROSERVICE_GRPC_NODEJS_ORDER_CHANNEL_ORDER_FOOD_PACKAGE_NAME =
  "vn.techres.microservice.grpc.nodejs_order_channel_order_food";

export interface OrderChannelOrderFoodServiceClient {
  getListOrder(request: GetListOrderRequest, metadata?: Metadata): Observable<ResultOrderResponse>;

  getOrderDetails(request: GetOrderDetailRequest, metadata?: Metadata): Observable<ResultOrderDetailResponse>;

  updateOrder(request: updateOrderRequest, metadata?: Metadata): Observable<BaseResponse>;

  getDetailBillAppFood(request: GetDetailBillAppFoodRequest, metadata?: Metadata): Observable<BillAppFoodBaseResponse>;

  getListChannelOrder(request: GetListChannelOrderRequest, metadata?: Metadata): Observable<ResultChannelOrderResponse>;

  updateOrderV2(request: UpdateOrderRequestV2, metadata?: Metadata): Observable<BaseResponse>;
}

export interface OrderChannelOrderFoodServiceController {
  getListOrder(
    request: GetListOrderRequest,
    metadata?: Metadata,
  ): Promise<ResultOrderResponse> | Observable<ResultOrderResponse> | ResultOrderResponse;

  getOrderDetails(
    request: GetOrderDetailRequest,
    metadata?: Metadata,
  ): Promise<ResultOrderDetailResponse> | Observable<ResultOrderDetailResponse> | ResultOrderDetailResponse;

  updateOrder(
    request: updateOrderRequest,
    metadata?: Metadata,
  ): Promise<BaseResponse> | Observable<BaseResponse> | BaseResponse;

  getDetailBillAppFood(
    request: GetDetailBillAppFoodRequest,
    metadata?: Metadata,
  ): Promise<BillAppFoodBaseResponse> | Observable<BillAppFoodBaseResponse> | BillAppFoodBaseResponse;

  getListChannelOrder(
    request: GetListChannelOrderRequest,
    metadata?: Metadata,
  ): Promise<ResultChannelOrderResponse> | Observable<ResultChannelOrderResponse> | ResultChannelOrderResponse;

  updateOrderV2(
    request: UpdateOrderRequestV2,
    metadata?: Metadata,
  ): Promise<BaseResponse> | Observable<BaseResponse> | BaseResponse;
}

export function OrderChannelOrderFoodServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getListOrder",
      "getOrderDetails",
      "updateOrder",
      "getDetailBillAppFood",
      "getListChannelOrder",
      "updateOrderV2",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OrderChannelOrderFoodService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OrderChannelOrderFoodService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ORDER_CHANNEL_ORDER_FOOD_SERVICE_NAME = "OrderChannelOrderFoodService";
